{
 "title": "Matrix Overview",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot)",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "ms-oce-gp-userprofile,ms-oce-gp-checkpermission"
   },
   {
    "name": "space",
    "label": "Space",
    "query": "label_values({exported_job=\"$application\"}, space)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes_gauge{exported_job=\"$application\", space=\"$space\"}) by (exported_instance)",
     "legendFormat": "Instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage_gauge{exported_job=\"$application\", space=\"$space\"}",
     "legendFormat": "Instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_gauge {exported_job=\"$application\", space=\"$space\"}",
     "legendFormat": "Instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Requests Success (per second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/oce/gp/.*\", status!~\"5.*\"}[1m])) by (exported_instance)",
     "legendFormat": "Instance {{exported_instance}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/oce/gp/.*\", status!~\"5.*\"}[1m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Requests Error (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/oce/gp/.*\", status=~\"5..\"}[1m]) * 60) by (exported_instance)",
     "legendFormat": "Instance {{exported_instance}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/oce/gp/.*\", status=~\"5..\"}[1m]) * 60)",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", space=\"$space\", uri=~\"/oce/gp/.*\", status!~\"5..\"}[1m])) by (exported_instance) / sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/oce/gp/.*\", status!~\"5..\"}[1m])) by (exported_instance)",
     "legendFormat": "Instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Backends Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/permission-delegation/v2/authorization.*\"}[1m]))",
     "legendFormat": "ACM"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", clientName=~\".*oce-fda-lookup.scapp-corp.swisscom.com\"}[1m]))",
     "legendFormat": "FDA Lookup"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", clientName=~\"blueadit-combox.*\"}[1m]))",
     "legendFormat": "Blueadit Combox"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/rest/mobile-management-registrations.*\"}[1m]))",
     "legendFormat": "Blueadit Prepaid"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", clientName=~\"mxp-activities.*\"}[1m]))",
     "legendFormat": "MUST"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/sis/.*\"}[1m]))",
     "legendFormat": "SIS"
    }
   ]
  },
  {
   "title": "Backends Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\", uri=~\"/permission-delegation/v2/authorization.*\"}[1m])) / sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/permission-delegation/v2/authorization.*\"}[1m]))",
     "legendFormat": "ACM"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\", clientName=~\".*oce-fda-lookup.scapp-corp.swisscom.com\"}[1m])) / sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", clientName=~\".*oce-fda-lookup.scapp-corp.swisscom.com\"}[1m]))",
     "legendFormat": "FDA Lookup"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\", clientName=~\"blueadit-combox.*\"}[1m])) / sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", clientName=~\"blueadit-combox.*\"}[1m]))",
     "legendFormat": "Blueadit Combox"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\", uri=~\"/rest/mobile-management-registrations.*\"}[1m])) / sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/rest/mobile-management-registrations.*\"}[1m]))",
     "legendFormat": "Blueadit Prepaid"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\", clientName=~\"mxp-activities.*\"}[1m])) / sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", clientName=~\"mxp-activities.*\"}[1m]))",
     "legendFormat": "MUST"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\", uri=~\"/sis/.*\"}[1m])) / sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\", uri=~\"/sis/.*\"}[1m]))",
     "legendFormat": "SIS"
    }
   ]
  }
 ]
}