{
 "title": "MiSe [Care]",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot)",
 "time": { "from": "2018-09-26T12:00:00.000Z", "to": "2018-09-26T13:30:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "ms-oce-soe-quickactions,ms-oce-gp-urlencryption,ms-oce-soe-callfilter,ms-oce-soe-contract,ms-oce-soe-puks,ms-oce-soe-priceAndBenefit,ms-oce-soe-deviceinformation,ms-oce-soe-ordernotifications,ms-oce-gp-encryptionservice,ms-oce-soe-serviceconfiguration,oce-soe-prepaidProductlisting,ms-oce-soe-simstatus,ms-oce-soe-userinteractions,ms-oce-soe-combox,ms-oce-gp-userpreferences,ms-oce-gp-common"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({exported_job=\"$application\", space=\"$space\"}, exported_instance)"
   },
   {
    "name": "space",
    "label": "Space",
    "query": "label_values({exported_job=\"$application\"}, space)"
   },
   {
    "name": "request_uri",
    "label": "Request  URI",
    "query": "label_values(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\"}, uri)"
   },
   {
    "name": "request_verb",
    "label": "Request Method",
    "query": "label_values(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",uri=~\"$request_uri.*\"}, method)"
   },
   {
    "name": "rest_client",
    "label": "REST Client",
    "query": "label_values(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\"}, clientName)"
   },
   {
    "name": "verb",
    "label": "REST Method",
    "query": "label_values(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",clientName=~\"$rest_client.*\",uri=~\"$rest_uri.*\"}, method)"
   },
   {
    "name": "rest_uri",
    "label": "REST URI",
    "query": "label_values(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",clientName=~\"$rest_client.*\"}, uri)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds_gauge{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds_gauge{exported_job=\"$application\",space=\"$space\",exported_instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes_gauge{exported_job=\"$application\",space=\"$space\",exported_instance=\"$instance\"})*100/sum(jvm_memory_max_bytes_gauge{exported_job=\"$application\",exported_instance=\"$instance\",space=\"$space\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes_gauge{exported_job=\"$application\",exported_instance=\"$instance\",space=\"$space\",area=\"nonheap\"})"
    }
   ]
  },
  { "title": "JVM Memory - Instanz $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "instance" },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "process_memory_rss_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_pss_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "pss"
    },
    {
     "expr": "process_memory_swap_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_swappss_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "swappss"
    },
    {
     "expr": "process_memory_pss_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"} + process_memory_swap_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "phys (pss+swap)"
    }
   ]
  },
  {
   "title": "JVM Native Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(process_virtual_memory_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"} + process_resident_memory_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}  - on(application,instance) sum(jvm_memory_committed_bytes_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"})  by(application,instance)) >= 0",
     "legendFormat": "native"
    }
   ]
  },
  { "title": "JVM Misc - Instanz $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "instance" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {},
    {
     "expr": "system_cpu_count_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "pcoess_threads{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "process_files_open_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_gauge{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Log Events (1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total_counter{exported_job=\"$application\",space=\"$space\",exported_instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap) - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "instance"
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes_gauge{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes_gauge{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes_gauge{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap) - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "instance"
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes_gauge{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes_gauge{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes_gauge{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Garbage Collection - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "instance"
  },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_duration_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    },
    {
     "expr": "rate(jvm_gc_pause_seconds_count{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_pause_duration_seconds_count{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}[1m])/increase(jvm_gc_pause_duration_seconds_count{export_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_duration_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    },
    {
     "expr": "increase(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/increase(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total_counter{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total_counter{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Classloading - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "repeat": "instance"
  },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class load/unload rate (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_gauge{exported_job=\"$application\",space=\"$space\",exported_instance=\"$instance\"}[5m])",
     "legendFormat": "class load rate"
    }
   ]
  },
  {
   "title": "Buffer Pools - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "repeat": "instance"
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes_gauge{application=\"$application\",space=\"$space\", exported_instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_gauge{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\", id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes_gauge{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes_gauge{application=\"$application\", space=\"$space\", exported_instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_gauge{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\", id=\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "HTTP Request Codes - Instanz $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"2.*\",uri=~\"$request_uri.*\",method=~\"$request_verb.*\"}[5m]))/sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"2.*\",uri=~\"$request_uri.*\",method=~\"$request_verb.*\"}[5m])) *1000",
     "legendFormat": "200er"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"5.*\",uri=~\"$request_uri.*\",method=~\"$request_verb.*\"}[5m]))/sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"5.*\",uri=~\"$request_uri.*\",method=~\"$request_verb.*\"}[5m])) *1000",
     "legendFormat": "500er"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"3.*\",uri=~\"$request_uri.*\",method=~\"$request_verb.*\" }[5m]))/sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"3.*\",uri=~\"$request_uri.*\",method=~\"$request_verb.*\"}[5m])) *1000",
     "legendFormat": "300er"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"4.*\",uri=~\"$request_uri.*\",method=~\"$request_verb.*\"}[5m]))/sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"4.*\",uri=~\"$request_uri.*\",method=~\"$request_verb.*\"}[5m])) *1000",
     "legendFormat": "400er"
    }
   ]
  },
  {
   "title": "Client Request - Instanz $instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"2.*\",clientName=~\"$rest_client.*\",uri=~\"$rest_uri.*\",method=~\"$verb.*\"}[5m]))/sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"2.*\",clientName=~\"$rest_client.*\",uri=~\"$rest_uri.*\",method=~\"$verb.*\"}[5m])) *1000",
     "legendFormat": "200er"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"3.*\",clientName=~\"$rest_client.*\",uri=~\"$rest_uri.*\",method=~\"$verb.*\"}[5m]))/sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"3.*\",clientName=~\"$rest_client.*\",uri=~\"$rest_uri.*\",method=~\"$verb.*\"}[5m])) *1000",
     "legendFormat": "300er"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"4.*\",clientName=~\"$rest_client.*\",uri=~\"$rest_uri.*\",method=~\"$verb.*\"}[5m]))/sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"4.*\",clientName=~\"$rest_client.*\",uri=~\"$rest_uri.*\",method=~\"$verb.*\"}[5m])) *1000",
     "legendFormat": "400er"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"5.*\",clientName=~\"$rest_client.*\",uri=~\"$rest_uri.*\",method=~\"$verb.*\"}[5m]))/sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"5.*\",clientName=~\"$rest_client.*\",uri=~\"$rest_uri.*\",method=~\"$verb.*\"}[5m])) *1000",
     "legendFormat": "500er"
    }
   ]
  }
 ]
}