{
 "title": "PlantillaMiSe",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot)",
 "time": { "from": "now-30m", "to": "now-1m" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "test-job" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({exported_job=\"$application\", space=\"$space\"}, exported_instance)"
   },
   {
    "name": "space",
    "label": "Space",
    "query": "label_values({exported_job=\"$application\"}, space)"
   },
   {
    "name": "req_verb",
    "label": "Request Method",
    "query": "label_values(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",uri=~\"$req_uri.*\"}, method)"
   },
   {
    "name": "req_uri",
    "label": "Request uri",
    "query": "label_values(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\"}, uri)"
   },
   {
    "name": "client",
    "label": "REST Client",
    "query": "label_values(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\"}, clientName)"
   },
   {
    "name": "verb",
    "label": "REST Method",
    "query": "label_values(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",clientName=~\"$client.*\",uri=~\"$uri.*\"}, method)"
   },
   {
    "name": "uri",
    "label": "REST uri",
    "query": "label_values(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",clientName=~\"$client.*\"}, uri)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{exported_job=\"$application\",space=\"$space\",exported_instance=\"$instance\"}*1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\",space=\"$space\",exported_instance=\"$instance\"})*100/sum(jvm_memory_max_bytes{exported_job=\"$application\",exported_instance=\"$instance\",space=\"$space\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{exported_job=\"$application\",exported_instance=\"$instance\",space=\"$space\",area=\"nonheap\"})"
      }
     ]
    }
   ]
  },
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"2.*\",uri=~\"$req_uri.*\",method=~\"$req_verb.*\" }[5m]))/sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"2.*\",uri=~\"$req_uri.*\",method=~\"$req_verb.*\"}[5m])) *1000",
     "legendFormat": "200er"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"5.*\",uri=~\"$req_uri.*\",method=~\"$req_verb.*\" }[5m]))/sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"5.*\",uri=~\"$req_uri.*\",method=~\"$req_verb.*\"}[5m])) *1000",
     "legendFormat": "500er"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"3.*\",uri=~\"$req_uri.*\",method=~\"$req_verb.*\" }[5m]))/sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"3.*\",uri=~\"$req_uri.*\",method=~\"$req_verb.*\"}[5m])) *1000",
     "legendFormat": "300er"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"4.*\",uri=~\"$req_uri.*\",method=~\"$req_verb.*\" }[5m]))/sum(rate(http_server_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"4.*\",uri=~\"$req_uri.*\",method=~\"$req_verb.*\"}[5m])) *1000",
     "legendFormat": "400er"
    }
   ]
  },
  {
   "title": "HTTP Rest Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"2.*\",clientName=~\"$client.*\",uri=~\"$uri.*\",method=~\"$verb.*\"}[5m]))/sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"2.*\",clientName=~\"$client.*\",uri=~\"$uri.*\",method=~\"$verb.*\"}[5m])) *1000",
     "legendFormat": "200er"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"5.*\",clientName=~\"$client.*\",uri=~\"$uri.*\",method=~\"$verb.*\"}[5m]))/sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"5.*\",clientName=~\"$client.*\",uri=~\"$uri.*\",method=~\"$verb.*\"}[5m])) *1000",
     "legendFormat": "500er"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"3.*\",clientName=~\"$client.*\",uri=~\"$uri.*\",method=~\"$verb.*\"}[5m]))/sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"3.*\",clientName=~\"$client.*\",uri=~\"$uri.*\",method=~\"$verb.*\"}[5m])) *1000",
     "legendFormat": "300er"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{exported_job=\"$application\", space=\"$space\",status=~\"4.*\",clientName=~\"$client.*\",uri=~\"$uri.*\",method=~\"$verb.*\"}[5m]))/sum(rate(http_client_requests_seconds_count{exported_job=\"$application\", space=\"$space\",status=~\"4.*\",clientName=~\"$client.*\",uri=~\"$uri.*\",method=~\"$verb.*\"}[5m])) *1000",
     "legendFormat": "400er"
    }
   ]
  },
  {
   "title": "JVM Memory - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"})",
       "legendFormat": "max"
      },
      {
       "expr": "process_memory_rss_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"} + process_memory_swap_bytes{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
       "legendFormat": "system-1m"
      },
      {},
      {
       "expr": "system_cpu_count{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "tomcat_threads{exported_job=\"$application\", space=\"$space\",exported_instance=\"$instance\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Log Events (1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{exported_job=\"$application\",space=\"$space\",exported_instance=\"$instance\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap) - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap) - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool Nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{exported_job=\"$application\", space=\"$space\" ,exported_instance=\"$instance\", area=\"nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Old Generation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ]
    },
    {
     "title": "Time Spend Paused on a GC",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class load/unload rate (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded{exported_job=\"$application\",space=\"$space\",exported_instance=\"$instance\"}[5m])",
       "legendFormat": "class load rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools - Instanz $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\",space=\"$space\", exported_instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{exported_job=\"$application\", space=\"$space\", exported_instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", space=\"$space\", exported_instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{exported_job=\"$application\", exported_instance=\"$instance\", space=\"$space\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}